# Generated by Django 3.2.17 on 2023-03-14 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Developer', 'Developer'), ('Banned', 'Banned')], default='User', max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Fee')),
                ('paid_fee', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Paid fee')),
                ('referrer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Active', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('city', models.CharField(max_length=20, verbose_name='Populated areas')),
                ('sold_currency', models.CharField(max_length=20, verbose_name='Sale currency')),
                ('sold_currency_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount of currency sold')),
                ('purchased_currency_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Amount of purchased currency')),
                ('currency_rate', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Exchange rate')),
                ('commission_fee', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Сommission')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_exchange_request', to='exchange.user')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
