# Generated by Django 3.2.17 on 2023-02-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_request_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='purchased_currency_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Amount of purchased currency'),
        ),
    ]
