# Generated by Django 3.2.17 on 2023-03-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_request_purchased_currency_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Developer', 'Developer'), ('Banned', 'Banned')], default='User', max_length=10),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
